package com.ak.keycepass.desktop.ui.screens

import androidx.compose.foundation.Image
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Download
import androidx.compose.material.icons.filled.QrCodeScanner
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.ak.keycepass.desktop.util.generateQRBitmap
import com.ak.keycepass.desktop.util.saveQRToFile
import java.io.File
import javax.swing.JFileChooser
import javax.swing.filechooser.FileNameExtensionFilter

@Composable
fun QRManagementScreen() {
    var selectedClasse by remember { mutableStateOf("B2_IT") }
    var selectedSemestre by remember { mutableStateOf("S2_2026") }
    var qrGenerated by remember { mutableStateOf(false) }
    var qrBitmap by remember { mutableStateOf<androidx.compose.ui.graphics.ImageBitmap?>(null) }

    Column(Modifier.fillMaxSize()) {
        Text(
            "Gestion des QR Codes",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.Bold
        )

        Spacer(Modifier.height(24.dp))

        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(24.dp)) {
            // Panneau de configuration
            Card(
                modifier = Modifier.weight(1f),
                shape = RoundedCornerShape(16.dp),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
            ) {
                Column(Modifier.padding(24.dp).fillMaxWidth()) {
                    Text("Générer un QR Code", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
                    Spacer(Modifier.height(20.dp))

                    Text("Classe", style = MaterialTheme.typography.labelLarge)
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = selectedClasse,
                        onValueChange = { selectedClasse = it },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true,
                        shape = RoundedCornerShape(12.dp)
                    )

                    Spacer(Modifier.height(16.dp))

                    Text("Semestre", style = MaterialTheme.typography.labelLarge)
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = selectedSemestre,
                        onValueChange = { selectedSemestre = it },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true,
                        shape = RoundedCornerShape(12.dp)
                    )

                    Spacer(Modifier.height(24.dp))

                    Button(
                        onClick = {
                            // Génération du vrai QR code
                            val content = "keycepass://attendance?class=${selectedClasse}:sem:${selectedSemestre}"
                            qrBitmap = generateQRBitmap(content, 400)
                            qrGenerated = true
                        },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Icon(
                            Icons.Default.QrCodeScanner,
                            contentDescription = null,
                            modifier = Modifier.size(18.dp)
                        )
                        Spacer(Modifier.width(8.dp))
                        Text("Générer le QR Code", Modifier.padding(vertical = 8.dp))
                    }
                }
            }

            // Aperçu QR
            Card(
                modifier = Modifier.weight(1f),
                shape = RoundedCornerShape(16.dp),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
            ) {
                Column(
                    Modifier.fillMaxSize().padding(24.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.Center
                ) {
                    if (qrGenerated && qrBitmap != null) {
                        Text("QR Code généré", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)

                        Spacer(Modifier.height(16.dp))

                        // Vrai QR code rendu
                        Surface(
                            modifier = Modifier.size(240.dp),
                            shape = RoundedCornerShape(12.dp),
                            color = MaterialTheme.colorScheme.surface,
                            tonalElevation = 4.dp
                        ) {
                            Box(Modifier.fillMaxSize().padding(16.dp)) {
                                Image(
                                    bitmap = qrBitmap!!,
                                    contentDescription = "QR Code $selectedClasse $selectedSemestre",
                                    modifier = Modifier.fillMaxSize()
                                )
                            }
                        }

                        Spacer(Modifier.height(16.dp))

                        Text(
                            "class:${selectedClasse}:sem:${selectedSemestre}",
                            style = MaterialTheme.typography.labelMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )

                        Spacer(Modifier.height(12.dp))

                        OutlinedButton(
                            onClick = {
                                val content = "keycepass://attendance?class=${selectedClasse}:sem:${selectedSemestre}"
                                val chooser = JFileChooser().apply {
                                    dialogTitle = "Exporter le QR Code"
                                    selectedFile = File("QR_${selectedClasse}_${selectedSemestre}.png")
                                    fileFilter = FileNameExtensionFilter("Images PNG (*.png)", "png")
                                }
                                if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
                                    var file = chooser.selectedFile
                                    if (!file.name.endsWith(".png")) {
                                        file = File(file.absolutePath + ".png")
                                    }
                                    saveQRToFile(content, file)
                                }
                            }
                        ) {
                            Icon(
                                Icons.Default.Download,
                                contentDescription = null,
                                modifier = Modifier.size(16.dp)
                            )
                            Spacer(Modifier.width(6.dp))
                            Text("Exporter PNG")
                        }
                    } else {
                        Text(
                            "Configurez la classe et le semestre,\npuis générez le QR Code",
                            style = MaterialTheme.typography.bodyLarge,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }
        }
    }
}
