package com.ak.keycepass.desktop.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

@Composable
fun QRManagementScreen() {
    var selectedClasse by remember { mutableStateOf("B2_IT") }
    var selectedSemestre by remember { mutableStateOf("S2_2026") }
    var qrGenerated by remember { mutableStateOf(false) }

    Column(Modifier.fillMaxSize()) {
        Text(
            "Gestion des QR Codes",
            style = MaterialTheme.typography.headlineMedium,
            fontWeight = FontWeight.Bold
        )

        Spacer(Modifier.height(24.dp))

        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.spacedBy(24.dp)) {
            // Panneau de configuration
            Card(
                modifier = Modifier.weight(1f),
                shape = RoundedCornerShape(16.dp),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
            ) {
                Column(Modifier.padding(24.dp).fillMaxWidth()) {
                    Text("Générer un QR Code", style = MaterialTheme.typography.titleLarge, fontWeight = FontWeight.Bold)
                    Spacer(Modifier.height(20.dp))

                    Text("Classe", style = MaterialTheme.typography.labelLarge)
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = selectedClasse,
                        onValueChange = { selectedClasse = it },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true,
                        shape = RoundedCornerShape(12.dp)
                    )

                    Spacer(Modifier.height(16.dp))

                    Text("Semestre", style = MaterialTheme.typography.labelLarge)
                    Spacer(Modifier.height(8.dp))
                    OutlinedTextField(
                        value = selectedSemestre,
                        onValueChange = { selectedSemestre = it },
                        modifier = Modifier.fillMaxWidth(),
                        singleLine = true,
                        shape = RoundedCornerShape(12.dp)
                    )

                    Spacer(Modifier.height(24.dp))

                    Button(
                        onClick = { qrGenerated = true },
                        modifier = Modifier.fillMaxWidth(),
                        shape = RoundedCornerShape(12.dp)
                    ) {
                        Text("📱 Générer le QR Code", Modifier.padding(vertical = 8.dp))
                    }
                }
            }

            // Aperçu QR
            Card(
                modifier = Modifier.weight(1f),
                shape = RoundedCornerShape(16.dp),
                elevation = CardDefaults.cardElevation(defaultElevation = 2.dp)
            ) {
                Column(
                    Modifier.fillMaxSize().padding(24.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.Center
                ) {
                    if (qrGenerated) {
                        Text("✅ QR Code généré !", style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold)

                        Spacer(Modifier.height(16.dp))

                        // Simulation visuelle du QR
                        Surface(
                            modifier = Modifier.size(200.dp),
                            shape = RoundedCornerShape(12.dp),
                            color = MaterialTheme.colorScheme.surfaceVariant
                        ) {
                            Column(
                                Modifier.fillMaxSize(),
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.Center
                            ) {
                                Text("⬛⬛⬛⬛⬛", fontSize = 24.sp, letterSpacing = 0.sp)
                                Text("⬛⬜⬜⬜⬛", fontSize = 24.sp, letterSpacing = 0.sp)
                                Text("⬛⬜⬛⬜⬛", fontSize = 24.sp, letterSpacing = 0.sp)
                                Text("⬛⬜⬜⬜⬛", fontSize = 24.sp, letterSpacing = 0.sp)
                                Text("⬛⬛⬛⬛⬛", fontSize = 24.sp, letterSpacing = 0.sp)
                            }
                        }

                        Spacer(Modifier.height(16.dp))

                        Text(
                            "class:${selectedClasse}:sem:${selectedSemestre}",
                            style = MaterialTheme.typography.labelMedium,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )

                        Spacer(Modifier.height(12.dp))

                        OutlinedButton(onClick = { /* Export PNG */ }) {
                            Text("💾 Exporter PNG")
                        }
                    } else {
                        Text(
                            "Configurez la classe et le semestre, puis générez le QR Code",
                            style = MaterialTheme.typography.bodyLarge,
                            color = MaterialTheme.colorScheme.onSurfaceVariant
                        )
                    }
                }
            }
        }
    }
}
